# Generated by Django 5.0.2 on 2024-03-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=45)),
                ('coursedescription', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=45)),
                ('packagedescription', models.CharField(max_length=250)),
                ('packageprice', models.CharField(max_length=250)),
            ],
        ),
    ]
