# Generated by Django 5.0.2 on 2024-03-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_course_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOptions',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('PackageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.package')),
            ],
        ),
    ]
